### PR TITLE
update magma IO syntax

### PR DESCRIPTION
**Pull request by hofstee**

### CODE REVIEW

**Comment by hofstee** [comment]
How do you append to IO with the new syntax?

**Comment by leonardt** [comment]
There's an open issue on this here: https://github.com/phanrahan/magma/issues/596

For now, the best way would be to incrementally construct a python dictionary ("appending" by adding keys to the dictionary), then passing the dict to IO

**Comment by leonardt** [comment]
Another option is to keep `IO` as a list and do a
```
io = m.IO(**{key: value for key, value in zip(IO[::2], IO[1::2])})
```

but i think this will trigger a different warning (mixing IO and io), so ideally you'd also rename the IO list to be something like `IO_`

**Comment by leonardt** [comment]
Manually fixing up these cases might be okay though, if writing the script is too tricky

**Comment by leonardt** [comment]
(Let me know if that's the case and I can go ahead and take care of the manual fixes)

**Comment by hofstee** [comment]
I think these might need to be manually handled. (Maybe you could still do `io += m.ClkInterface()`?)

**Pull request merged**
