### PR TITLE
Fix deadlock in subprocess logic

### PR DESCRIPTION
**Pull request by leonardt**
See
https://stackoverflow.com/questions/1445627/how-can-i-find-out-why-subprocess-popen-wait-waits-forever-if-stdout-pipe
for some more details

### CODE REVIEW

**Comment by Kuree** [comment]
@leonardt Do you want me to try out Github actions instead of Travis? Github actions uses latest OSX.

**Comment by leonardt** [comment]
@Kuree sure, but I'm not exactly sure if this issue is fixed with the latest OS X, looking into it now, I think perhaps the verilator version on homebrew got updated and now it's not working with the travis environment

**Comment by Kuree** [comment]
My guess is that the apple clang came with the OSX image is too old. Switching to newest image should help.

**Comment by Kuree** [comment]
@leonardt See https://github.com/leonardt/fault/pull/238, which fixes the macos issue via Github Actions.

**Pull request merged**
